import { PrelimsAnalysisView } from '@/components/analise/PrelimsAnalysisView';
import type { PrelimsAnalise } from '@/types/analise';

const analise: PrelimsAnalise = {
  id: 'kondratavicius-vs-trocoli',
  evento_id: null,
  slug: 'kondratavicius-vs-trocoli',
  titulo: 'Kondratavicius vs Trocoli',
  subtitulo: null,
  lutador1_id: null,
  lutador2_id: null,
  artigo_conteudo: '',
  tactical_breakdown: {
    stats: [],
    radarData: [],
    taleOfTape: {
      fighter1: { altura: '', envergadura: '', idade: 0, academia: '' },
      fighter2: { altura: '', envergadura: '', idade: 0, academia: '' },
    },
    pathsToVictory: { fighter1: [], fighter2: [] },
    dangerZones: [],
  },
  fight_prediction: {
    predictedWinner: 'fighter1',
    predictedMethod: 'KO/TKO R1',
    confidence: 'MEDIA',
    fighter1Scenarios: [],
    fighter2Scenarios: [],
    keyFactors: [],
    xFactor: { title: '', description: '' },
  },
  fighter1_info: {
    nome: 'Mantas Kondratavicius',
    record: '8-1-0',
    ultimasLutas: [],
  },
  fighter2_info: {
    nome: 'Antonio Trocoli',
    record: '12-6-0',
    ultimasLutas: [],
  },
  evento_nome: 'UFC Fight Night: Evloev vs Murphy',
  evento_data: '21 de Marco, 2026',
  evento_local: 'The O2 Arena, Londres, Reino Unido',
  categoria_peso: 'Peso Medio (185 lbs)',
  num_rounds: 3,
  is_titulo: false,
  broadcast: null,
  status: 'published',
  analysis_type: 'prelims',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),

  prelims_analysis: {
    hero: {
      evento_nome: 'UFC Fight Night: Evloev vs Murphy',
      evento_data: '21 de Marco, 2026',
      categoria_peso: 'Peso Medio (185 lbs)',
      num_rounds: 3,
      is_titulo: false,
      fighter1: {
        nome: 'Kondratavicius',
        record: '8-1-0',
        ranking: undefined,
      },
      fighter2: {
        nome: 'Trocoli',
        record: '12-6-0',
        ranking: undefined,
      },
    },

    comparacao_estatistica: {
      stats: [
        {
          label: 'Sig. Strikes por Minuto',
          valueA: 5.45,
          valueB: 3.20,
          maxVal: 8,
          format: 'decimal',
          note: 'Kondratavicius e muito mais ativo no striking, quase o dobro do volume de Trocoli',
        },
        {
          label: 'Precisao de Strikes (%)',
          valueA: 58,
          valueB: 42,
          maxVal: 100,
          format: 'percent',
          note: 'Precisao significativamente superior do lituano, conecta quase 6 em cada 10',
        },
        {
          label: 'Strikes Absorvidos/Min',
          valueA: 3.20,
          valueB: 5.80,
          maxVal: 8,
          format: 'decimal',
          reverseWinner: true,
          note: 'Trocoli absorve quase 6 golpes por minuto, numero extremamente preocupante',
        },
        {
          label: 'Defesa de Strikes (%)',
          valueA: 55,
          valueB: 38,
          maxVal: 100,
          format: 'percent',
          note: 'Trocoli defende menos de 40% dos strikes, vulnerabilidade enorme',
        },
        {
          label: 'Takedowns por 15 Min',
          valueA: 0.90,
          valueB: 1.10,
          maxVal: 5,
          format: 'decimal',
        },
        {
          label: 'Precisao de Takedown (%)',
          valueA: 50,
          valueB: 33,
          maxVal: 100,
          format: 'percent',
        },
        {
          label: 'Defesa de Takedown (%)',
          valueA: 70,
          valueB: 55,
          maxVal: 100,
          format: 'percent',
          note: 'Kondratavicius defende takedowns de forma solida',
        },
      ],
      tale_of_tape: [
        { label: 'Idade', fighter1: '26 anos', fighter2: '35 anos', note: 'Kondratavicius e 9 anos mais jovem' },
        { label: 'Altura', fighter1: '1,91m (6\'3")', fighter2: '1,96m (6\'5")', note: 'Trocoli tem 5cm de vantagem na altura' },
        { label: 'Envergadura', fighter1: '192cm (75.5")', fighter2: '209cm (82")', note: 'Trocoli tem 6.5 polegadas a mais de envergadura, diferenca enorme' },
        { label: 'Stance', fighter1: 'Ortodoxo', fighter2: 'Ortodoxo', note: null },
        { label: 'Academia', fighter1: 'Fighter House / Kaunas, Lituania', fighter2: 'Team Malvado / Brasil', note: null },
      ],
    },

    historico_lutas: {
      fighter1: {
        nome: 'Kondratavicius',
        recent_fights: [
          {
            date: 'Set 2025',
            opponent: 'Djani Barbir',
            result: 'W',
            method: 'TKO R1 (socos, 1:06)',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'TKO em 66 segundos no DWCS contra invicto. Ganhou contrato com o UFC de forma dominante.',
          },
          {
            date: 'Mar 2025',
            opponent: 'Michael Tchamou',
            result: 'W',
            method: 'KO R1',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Nocaute no primeiro round contra um dos melhores strikers do Cage Warriors.',
          },
          {
            date: 'Jan 2024',
            opponent: 'Kirill Lumivouri',
            result: 'W',
            method: 'Sub R1',
            opponent_rank: 'N/R',
            quality_score: 1,
            quality_label: 'Ruim',
            note: 'Finalizacao no primeiro round, mostrou versatilidade alem do striking.',
          },
          {
            date: 'Jun 2023',
            opponent: 'Virgil Augene',
            result: 'L',
            method: 'TKO R1',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Unica derrota da carreira no ARES FC. Foi parado no primeiro round.',
          },
          {
            date: 'Fev 2023',
            opponent: 'Titos Mokbel',
            result: 'W',
            method: 'KO R1',
            opponent_rank: 'N/R',
            quality_score: 1,
            quality_label: 'Ruim',
            note: 'Mais um nocaute no primeiro round, padrao de finalizacao rapida.',
          },
        ],
      },
      fighter2: {
        nome: 'Trocoli',
        recent_fights: [
          {
            date: 'Dez 2025',
            opponent: 'Mansur Abdul-Malik',
            result: 'L',
            method: 'Sub R1 (guilhotina, 1:09)',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Finalizado em pouco mais de 1 minuto no UFC 323. Terceira derrota consecutiva.',
          },
          {
            date: 'Nov 2024',
            opponent: 'Tresean Gore',
            result: 'L',
            method: 'Sub R1 (guilhotina, 1:23)',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Finalizado novamente por guilhotina no primeiro round. Padrao preocupante.',
          },
          {
            date: 'Jun 2024',
            opponent: 'Shara Magomedov',
            result: 'L',
            method: 'TKO R3',
            opponent_rank: 'N/R',
            quality_score: 4,
            quality_label: 'Muito Bom',
            note: 'Aguento 3 rounds contra Shara Bullet em Riyadh, aceito em cima da hora. Adversario de altissimo nivel.',
          },
          {
            date: 'Nov 2021',
            opponent: 'Reslley Isael',
            result: 'W',
            method: 'Sub R1 (mata-leao, 2:10)',
            opponent_rank: 'N/R',
            quality_score: 1,
            quality_label: 'Ruim',
            note: 'Ultima vitoria da carreira, finalizacao rapida no Brazilian Fighting Series. Desde entao, 3 derrotas consecutivas no UFC.',
          },
          {
            date: 'Jul 2019',
            opponent: 'Kenneth Bergh',
            result: 'NC',
            method: 'NC (falhou teste antidoping)',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Venceu por finalizacao no DWCS e ganhou contrato, mas resultado foi anulado por falha no antidoping. Contrato rescindido.',
          },
        ],
      },
    },

    perfil_habilidades: {
      skills: [
        {
          label: 'Striking em Pe',
          valueA: 78,
          valueB: 62,
          labelA: 'Muito Bom',
          labelB: 'Bom',
          advantage: 'fighter1',
          advantage_note: 'Kondratavicius tem precisao superior (58%) e volume maior. Trocoli depende mais de finalizacoes no chao do que striking.',
        },
        {
          label: 'Poder de Nocaute',
          valueA: 82,
          valueB: 72,
          labelA: 'Muito Bom',
          labelB: 'Bom',
          advantage: 'fighter1',
          advantage_note: 'Kondratavicius tem poder de nocaute superior com 75% de vitorias por KO. Trocoli tem apenas 25% de KOs e depende mais de finalizacoes.',
        },
        {
          label: 'Wrestling e Grappling',
          valueA: 55,
          valueB: 50,
          labelA: 'Bom',
          labelB: 'Medio',
          advantage: 'even',
          advantage_note: 'Nenhum dos dois e um grappler de elite. Trocoli foi finalizado duas vezes por guilhotina, vulnerabilidade clara.',
        },
        {
          label: 'Defesa Geral',
          valueA: 60,
          valueB: 35,
          labelA: 'Bom',
          labelB: 'Medio',
          advantage: 'fighter1',
          advantage_note: 'Trocoli defende apenas 38% dos strikes e foi finalizado 3 vezes em sequencia. Defesa muito preocupante.',
        },
        {
          label: 'Cardio e Ritmo',
          valueA: 55,
          valueB: 52,
          labelA: 'Bom',
          labelB: 'Medio',
          advantage: 'even',
          advantage_note: 'Ambos preferem resolver no primeiro round. Se a luta for para a distancia, nenhum tem vantagem clara.',
        },
        {
          label: 'Experiencia no Octagon',
          valueA: 30,
          valueB: 55,
          labelA: 'Ruim',
          labelB: 'Bom',
          advantage: 'fighter2',
          advantage_note: 'Trocoli tem 3 lutas no UFC (0V-3D) e enfrentou Shara Magomedov. Kondratavicius faz sua estreia no Octagon.',
        },
      ],
      insight: 'Kondratavicius e um finalizador nato que nunca precisou dos juizes, vencendo 100% das suas lutas por nocaute ou finalizacao. Trocoli tem experiencia no UFC mas vem de 3 derrotas consecutivas (todas por finalizacao no R1) com defesa em colapso total. O lituano entra como favorito claro apesar de ser estreante.',
    },

    distribuicao_vitorias: {
      fighter1: {
        nome: 'Kondratavicius',
        ko_tko: { count: 6, percent: 75 },
        submission: { count: 2, percent: 25 },
        decision: { count: 0, percent: 0 },
        total_wins: 8,
      },
      fighter2: {
        nome: 'Trocoli',
        ko_tko: { count: 3, percent: 25 },
        submission: { count: 5, percent: 42 },
        decision: { count: 4, percent: 33 },
        total_wins: 12,
      },
      insight: 'Kondratavicius nunca venceu por decisao. Todas as suas 8 vitorias foram por nocaute (75%) ou finalizacao (25%), todas no primeiro round. Trocoli e mais um finalizador de chao com 42% de vitorias por submissao e apenas 25% por KO, mas vem sendo finalizado sistematicamente nos ultimos 3 combates. Essa luta provavelmente vai ser decidida nos primeiros minutos.',
    },

    previsao_final: {
      winner_name: 'Kondratavicius',
      winner_side: 'fighter1',
      predicted_method: 'KO/TKO R1',
      confidence_score: 7,
      confidence_label: 'MEDIA-ALTA',
      explanation: 'Mantas Kondratavicius e um prospecto genuino com 100% de finalizacoes na carreira e poder explosivo que ganhou um contrato no DWCS em 66 segundos. Trocoli vem de 3 derrotas consecutivas, todas por finalizacao no primeiro round, com defesa de strikes de apenas 38%. O brasileiro tem experiencia e poder, mas esta em queda livre no momentum. O lituano deve impor seu ritmo desde o primeiro segundo e aproveitar as lacunas defensivas de Trocoli para buscar o nocaute rapido.',
      x_factor: {
        title: 'A taxa de finalizacao de Kondratavicius',
        description: '100% de finalizacoes na carreira. Kondratavicius nunca precisou dos juizes e termina lutas com brutalidade. Se Trocoli nao tiver respeito maximo pelo poder do lituano, vai para o chao rápido.',
      },
      upset_alert: {
        title: 'O alcance de Trocoli pode fazer a diferenca',
        description: 'Com 6.5 polegadas a mais de envergadura e 5cm de altura, Trocoli pode manter distancia e usar o jab. Apesar de vir de 3 derrotas, aguentou 3 rounds contra Shara Magomedov e tem experiencia no Octagon. Se Kondratavicius entrar sem respeitar o alcance, pode ser surpreendido.',
      },
      probabilities: {
        fighter1: { nome: 'Kondratavicius', percent: 68 },
        fighter2: { nome: 'Trocoli', percent: 30 },
        draw: 2,
      },
      value_picks: {
        moneyline: { pick: 'Kondratavicius (-800)', reasoning: 'Favorito massivo e justificado. 100% de finalizacoes, TKO em 66 segundos no DWCS. Trocoli 0-3 no UFC com 3 derrotas no R1. O preco e alto mas o risco e baixo.' },
        method: { pick: 'Kondratavicius por KO/TKO R1', reasoning: 'Kondratavicius nunca precisou de mais de 1 round. Trocoli tem 38% de defesa de strikes e foi finalizado nas ultimas 3. A convergencia e total.' },
        over_under: { pick: 'Under 1.5 Rounds', rounds: 1.5, reasoning: 'As ultimas 3 derrotas de Trocoli foram todas no R1 (Magomedov, Gore, Abdul-Malik). Kondratavicius finaliza no R1 sistematicamente. Probabilidade altissima de acabar cedo.' },
        best_value: 'Kondratavicius por KO/TKO R1 e quase certo. O preco nao vai ser bom, mas combinado com Under 1.5 pode render.',
      },
    },
  },
};

export default function Page() {
  return <PrelimsAnalysisView analise={analise} />;
}
