import { chromium } from 'playwright';
import { createHmac } from 'crypto';
const ts = Date.now().toString();
const sig = createHmac('sha256', 'ufc-admin-2024').update(ts).digest('hex');
const browser = await chromium.launch({ headless: true });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 1300 }, deviceScaleFactor: 2 });
await ctx.addCookies([{ name: 'admin_token', value: `${ts}.${sig}`, domain: 'localhost', path: '/', httpOnly: false, secure: false, sameSite: 'Lax' }]);
const page = await ctx.newPage();
await page.goto('http://localhost:3010/pt/hub/analise/evento/prochazka-vs-ulberg', { waitUntil: 'networkidle', timeout: 60000 });
await page.waitForTimeout(1500);
await page.screenshot({ path: '/tmp/event-top.png', fullPage: false });
await page.evaluate(() => window.scrollBy(0, 800));
await page.waitForTimeout(400);
await page.screenshot({ path: '/tmp/event-mid.png', fullPage: false });
await page.evaluate(() => window.scrollBy(0, 800));
await page.waitForTimeout(400);
await page.screenshot({ path: '/tmp/event-bot.png', fullPage: false });
await browser.close();
console.log('OK');
