import { RecapView } from '@/components/recap/RecapView';
import { enrichRecapWithPhotos } from '@/lib/enrich-recap-photos';
import type { RecapData } from '@/types/recap';
import type { EventCreatorKitData } from '@/types/event-creator-kit';

export const dynamic = 'force-dynamic';

const recapData: RecapData = {
  evento_nome: 'UFC Fight Night: Evloev vs Murphy',
  evento_data: '21 de Marco, 2026',
  evento_local: 'The O2 Arena, Londres, Inglaterra',
  evento_numero: 'UFC Fight Night 270',

  total_fights: 13,
  predictions_correct: 11,
  methods_correct: 5,

  main_card: [
    {
      slug: 'evloev-vs-murphy',
      fighter1: { nome: 'Movsar Evloev', record: '20-0-0' },
      fighter2: { nome: 'Lerone Murphy', record: '17-1-1' },
      categoria_peso: 'Peso Pena (145 lbs)',
      num_rounds: 5,
      is_main_event: true,
      predicted_winner: 'Movsar Evloev',
      predicted_method: 'Decisao Unanime',
      confidence_label: 'MEDIA',
      actual_winner: 'Movsar Evloev',
      actual_method: 'Decisao Majoritaria',
      actual_round: 5,
      actual_time: '25:00',
      prediction_correct: true,
      method_correct: true,
      recap_note: 'Luta controversa. Evloev levou ponto descontado no R4 por golpe baixo mas ainda assim venceu por decisao majoritaria (48-46, 48-46, 47-47). Murphy pareceu dominar os primeiros rounds no striking e sofreu lesao no quadril no R3. Evloev completou takedown importante no R5. Aljamain Sterling e varios analistas questionaram os scorecards.',
    },
    {
      slug: 'riley-vs-aswell-jr',
      fighter1: { nome: 'Luke Riley', record: '13-0-0' },
      fighter2: { nome: 'Michael Aswell Jr.', record: '11-4-0' },
      categoria_peso: 'Peso Pena (145 lbs)',
      num_rounds: 3,
      predicted_winner: 'Luke Riley',
      predicted_method: 'KO/TKO R1-R2',
      confidence_label: 'MEDIA-ALTA',
      actual_winner: 'Luke Riley',
      actual_method: 'Decisao Unanime',
      actual_round: 3,
      actual_time: '15:00',
      prediction_correct: true,
      method_correct: false,
      recap_note: 'Riley venceu de forma dominante (30-27 x3) mas nao conseguiu a finalizacao. Aswell mostrou queixo forte e resiliencia. Riley mantem o invicto em 13-0.',
    },
    {
      slug: 'page-vs-patterson',
      fighter1: { nome: 'Michael Page', record: '25-3-0' },
      fighter2: { nome: 'Sam Patterson', record: '14-3-1' },
      categoria_peso: 'Peso Meio-Medio (170 lbs)',
      num_rounds: 3,
      predicted_winner: 'Sam Patterson',
      predicted_method: 'Decisao Unanime',
      confidence_label: 'MEDIA',
      actual_winner: 'Michael Page',
      actual_method: 'Decisao Unanime',
      actual_round: 3,
      actual_time: '15:00',
      prediction_correct: false,
      method_correct: false,
      recap_note: 'NOSSO MAIOR ERRO DO CARD. Page neutralizou completamente o grappling de Patterson, defendendo takedowns e controlando a distancia. Dana White saiu da arena durante essa luta por falta de acao. MVP mostrou que conhecer o jogo do adversario funciona pros dois lados.',
    },
    {
      slug: 'baraniewski-vs-lane',
      fighter1: { nome: 'Iwo Baraniewski', record: '8-0-0' },
      fighter2: { nome: 'Austen Lane', record: '13-8-0' },
      categoria_peso: 'Peso Meio-Pesado (205 lbs)',
      num_rounds: 3,
      predicted_winner: 'Iwo Baraniewski',
      predicted_method: 'KO/TKO R1',
      confidence_label: 'MEDIA-ALTA',
      actual_winner: 'Iwo Baraniewski',
      actual_method: 'TKO R1 (socos)',
      actual_round: 1,
      actual_time: '0:28',
      prediction_correct: true,
      method_correct: true,
      bonus: 'POTN',
      recap_note: 'Exatamente como previmos. Baraniewski conectou um combo de dois socos que derrubou Lane, depois finalizou com ground and pound em 28 segundos. Bonus de $100K de Performance da Noite. Terceiro nocaute consecutivo no R1.',
    },
    {
      slug: 'dolidze-vs-duncan',
      fighter1: { nome: 'Roman Dolidze', record: '15-5-0' },
      fighter2: { nome: 'Christian Leroy Duncan', record: '14-2-0' },
      categoria_peso: 'Peso Medio (185 lbs)',
      num_rounds: 3,
      predicted_winner: 'Christian Leroy Duncan',
      predicted_method: 'KO/TKO R1-R2',
      confidence_label: 'MEDIA',
      actual_winner: 'Christian Leroy Duncan',
      actual_method: 'Decisao Unanime',
      actual_round: 3,
      actual_time: '15:00',
      prediction_correct: true,
      method_correct: false,
      recap_note: 'Acertamos o vencedor mas erramos o metodo. Duncan venceu por decisao (29-28 x3) em vez do KO previsto. Dolidze foi agressivo nos takedowns no inicio mas Duncan defendeu bem e dominou no striking. A envergadura de CLD fez a diferenca na distancia.',
    },
    {
      slug: 'campbell-vs-silva',
      fighter1: { nome: 'Kurtis Campbell', record: '8-1-0' },
      fighter2: { nome: 'Danny Silva', record: '11-2-0' },
      categoria_peso: 'Peso Pena (145 lbs)',
      num_rounds: 3,
      predicted_winner: 'Kurtis Campbell',
      predicted_method: 'KO/TKO R1-R2',
      confidence_label: 'MEDIA',
      actual_winner: 'Danny Silva',
      actual_method: 'TKO R2 (socos)',
      actual_round: 2,
      actual_time: '0:31',
      prediction_correct: false,
      method_correct: false,
      recap_note: 'UPSET DO CARD. Silva derrubou Campbell com um gancho de direita devastador e finalizou com mais dois diretos. A Pantera Rosa sofreu sua primeira derrota na carreira no debut do UFC. Provamos que alertamos sobre o risco de debuts imprevisíveis, mas escolhemos o lado errado.',
    },
  ],
  prelims: [
    {
      slug: 'jones-vs-sola',
      fighter1: { nome: 'Mason Jones', record: '18-2-0' },
      fighter2: { nome: 'Axel Sola', record: '11-1-1' },
      categoria_peso: 'Peso Leve (155 lbs)',
      num_rounds: 3,
      predicted_winner: 'Mason Jones',
      predicted_method: 'Decisao Unanime',
      confidence_label: 'MEDIA',
      actual_winner: 'Mason Jones',
      actual_method: 'Decisao Unanime',
      actual_round: 3,
      actual_time: '15:00',
      prediction_correct: true,
      method_correct: true,
      bonus: 'FOTN',
      recap_note: 'Acerto perfeito: vencedor E metodo. Uma guerra sangrenta de 3 rounds que rendeu Fight of the Night com $100K pra cada. Jones e Sola deram um show.',
    },
    {
      slug: 'wood-vs-keita',
      fighter1: { nome: 'Nathaniel Wood', record: '23-6-0' },
      fighter2: { nome: 'Losene Keita', record: '16-2-0' },
      categoria_peso: 'Peso Pena (145 lbs)',
      num_rounds: 3,
      predicted_winner: 'Nathaniel Wood',
      predicted_method: 'Decisao Unanime',
      confidence_label: 'MEDIA',
      actual_winner: 'Nathaniel Wood',
      actual_method: 'Decisao Dividida',
      actual_round: 3,
      actual_time: '15:00',
      prediction_correct: true,
      method_correct: true,
      recap_note: 'Acertamos o azarao! Wood venceu Keita por decisao dividida (29-28, 29-28, 28-29). O veteranismo e o fight IQ prevaleceram sobre o hype do estreante, como previmos.',
    },
    {
      slug: 'sutherland-vs-pericic',
      fighter1: { nome: 'Louie Sutherland', record: '10-5-0' },
      fighter2: { nome: 'Brando Pericic', record: '6-1-0' },
      categoria_peso: 'Peso Pesado (265 lbs)',
      num_rounds: 3,
      predicted_winner: 'Brando Pericic',
      predicted_method: 'KO/TKO R1',
      confidence_label: 'MEDIA',
      actual_winner: 'Brando Pericic',
      actual_method: 'TKO R1 (strikes)',
      actual_round: 1,
      actual_time: '1:48',
      prediction_correct: true,
      method_correct: true,
      recap_note: 'Acerto perfeito. Pericic finalizou Sutherland no R1 por TKO com strikes, exatamente como previmos. O pupilo do City Kickboxing continua impressionando.',
    },
    {
      slug: 'kondratavicius-vs-trocoli',
      fighter1: { nome: 'Mantas Kondratavicius', record: '9-1-0' },
      fighter2: { nome: 'Antonio Trocoli', record: '12-7-0' },
      categoria_peso: 'Peso Medio (185 lbs)',
      num_rounds: 3,
      predicted_winner: 'Mantas Kondratavicius',
      predicted_method: 'KO/TKO R1',
      confidence_label: 'MEDIA-ALTA',
      actual_winner: 'Mantas Kondratavicius',
      actual_method: 'Decisao Unanime',
      actual_round: 3,
      actual_time: '15:00',
      prediction_correct: true,
      method_correct: false,
      recap_note: 'Vencedor correto, metodo errado. Kondratavicius dominou mas Trocoli mostrou queixo e sobreviveu 3 rounds (30-27, 29-27, 29-27). Trocoli e mais duro do que as 3 derrotas consecutivas sugeriam.',
    },
    {
      slug: 'pinto-vs-franco',
      fighter1: { nome: 'Mario Pinto', record: '12-0-0' },
      fighter2: { nome: 'Felipe Franco', record: '10-2-0' },
      categoria_peso: 'Peso Pesado (265 lbs)',
      num_rounds: 3,
      predicted_winner: 'Mario Pinto',
      predicted_method: 'TKO R2',
      confidence_label: 'MEDIA-ALTA',
      actual_winner: 'Mario Pinto',
      actual_method: 'Decisao Unanime',
      actual_round: 3,
      actual_time: '15:00',
      prediction_correct: true,
      method_correct: false,
      recap_note: 'Vencedor correto, metodo errado. Pinto dominou mas Franco mostrou corage e sobreviveu 3 rounds (29-28 x3). Pinto segue invicto em 12-0.',
    },
    {
      slug: 'rock-vs-al-selwady',
      fighter1: { nome: 'Shem Rock', record: '12-3-1' },
      fighter2: { nome: 'Abdul-Kareem Al-Selwady', record: '16-4-0' },
      categoria_peso: 'Peso Leve (155 lbs)',
      num_rounds: 3,
      predicted_winner: 'Abdul-Kareem Al-Selwady',
      predicted_method: 'TKO R2',
      confidence_label: 'MEDIA',
      actual_winner: 'Abdul-Kareem Al-Selwady',
      actual_method: 'Decisao Unanime',
      actual_round: 3,
      actual_time: '15:00',
      prediction_correct: true,
      method_correct: false,
      recap_note: 'Vencedor correto, metodo errado. Al-Selwady dominou no striking (30-27 x3) mas Rock sobreviveu com o jiu-jitsu defensivo. Primeira vitoria UFC pros dois nessa revanche de estreias perdidas.',
    },
    {
      slug: 'dyer-vs-oliveira',
      fighter1: { nome: 'Shanelle Dyer', record: '7-1-0' },
      fighter2: { nome: 'Ravena Oliveira', record: '7-4-1' },
      categoria_peso: 'Peso Palha Feminino (115 lbs)',
      num_rounds: 3,
      predicted_winner: 'Shanelle Dyer',
      predicted_method: 'Decisao Unanime',
      confidence_label: 'MEDIA',
      actual_winner: 'Shanelle Dyer',
      actual_method: 'TKO R2 (head kick + socos)',
      actual_round: 2,
      actual_time: '1:17',
      prediction_correct: true,
      method_correct: false,
      bonus: 'POTN',
      recap_note: 'Acertamos o vencedor mas subestimamos o poder de Dyer. Nocauteou Oliveira com head kick seguido de socos no R2. Performance da Noite com bonus de $100K. Debut espetacular.',
    },
  ],

  headlines: [
    { icon: 'AlertTriangle', title: 'Controversia no Main Event', description: 'Evloev vence Murphy por decisao majoritaria controversa (48-46, 48-46, 47-47) mesmo com ponto descontado no R4. Aljamain Sterling e comunidade MMA questionam os scorecards.', tag: 'CONTROVERSIA' },
    { icon: 'Zap', title: 'Baraniewski: 28 Segundos e $100K', description: 'O polones invicto nocauteou Lane em 28 segundos e faturou bonus de Performance da Noite. Terceiro nocaute no R1 consecutivo.', fighter: 'Baraniewski', tag: 'FINISH' },
    { icon: 'TrendingUp', title: 'O Upset da Pantera Rosa', description: 'Danny Silva nocauteou o invicto Kurtis Campbell no R2 com um gancho de direita devastador. A festa do debut virou pesadelo pra Liverpool.', fighter: 'Silva', tag: 'UPSET' },
    { icon: 'Target', title: 'Jones vs Sola: Guerra do Ano', description: 'Mason Jones e Axel Sola protagonizaram uma guerra sangrenta de 3 rounds que rendeu Fight of the Night. $100K pra cada.', tag: 'FOTN' },
    { icon: 'Brain', title: 'MVP Frustra Patterson e Dana White', description: 'Page venceu Patterson por decisao unanime mas a falta de acao fez Dana White sair da arena. O sparring partner nao conseguiu implementar o grappling.', fighter: 'Page', tag: 'DECISAO' },
    { icon: 'Sparkles', title: 'Dyer: Head Kick e $100K no Debut', description: 'Shanelle Dyer nocauteou Oliveira com head kick no R2 e ganhou Performance da Noite no debut. A britanica chegou com tudo.', fighter: 'Dyer', tag: 'DEBUT' },
  ],

  star_of_the_night: {
    fighter: 'Iwo Baraniewski',
    stat_line: '8-0 | TKO R1 (0:28) | $100K POTN | 3 nocautes no R1 seguidos',
    narrative: 'Baraniewski confirma que o hype e real. Em 28 segundos, despachou o gigante da NFL Austen Lane com um combo de dois socos que paralisou o O2 Arena. Tres lutas profissionais, tres nocautes no primeiro round, incluindo um de 20 segundos no DWCS. O polones de 27 anos e o prospect mais explosivo do meio-pesado e agora tem $100K a mais no bolso pra provar. A questao nao e se ele vai chegar ao top 15, e quando.',
  },

  ranking_moves: [
    { fighter: 'Movsar Evloev', division: 'Peso Pena', from: 1, to: 1, direction: 'up' },
    { fighter: 'Lerone Murphy', division: 'Peso Pena', from: 3, to: 5, direction: 'down' },
    { fighter: 'Christian Leroy Duncan', division: 'Peso Medio', from: null, to: 15, direction: 'new' },
    { fighter: 'Luke Riley', division: 'Peso Pena', from: null, to: 15, direction: 'new' },
  ],

  whats_next: [
    { fighter: 'Movsar Evloev', result: 'W', potential_opponents: ['Alexander Volkanovski', 'Ilia Topuria'], narrative: 'Evloev e agora o desafiante numero 1 ao titulo peso-pena. Com 20-0, e o lutador invicto mais dominante da divisao. O proximo passo e o titulo.' },
    { fighter: 'Lerone Murphy', result: 'L', potential_opponents: ['Diego Lopes', 'Arnold Allen', 'Yair Rodriguez'], narrative: 'A primeira derrota da carreira veio de forma controversa. Murphy precisa voltar contra um top 5 pra se manter na conversa pelo titulo. Diego Lopes seria a luta perfeita.' },
    { fighter: 'Michael Page', result: 'W', potential_opponents: ['Geoff Neal', 'Ian Garry rematch'], narrative: 'MVP vence a quarta em cinco no UFC mas a performance tediosa contra Patterson nao impressionou. Precisa de uma luta empolgante pro proximo card.' },
    { fighter: 'Christian Leroy Duncan', result: 'W', potential_opponents: ['Robert Whittaker', 'Jared Cannonier', 'Paulo Costa'], narrative: 'Duncan entra no ranking com 4 vitorias seguidas. Merece um top 10 no proximo card. O britanico e um dos nomes mais quentes do peso-medio.' },
    { fighter: 'Danny Silva', result: 'W', potential_opponents: ['Prospect ranqueado', 'Outro debutante promissor'], narrative: 'O upset sobre Campbell da nova vida a carreira de Silva. Com 3-1 no UFC, pode escalar rapidamente no peso-pena.' },
  ],

  bonuses: {
    fotn: { fighter1: 'Mason Jones', fighter2: 'Axel Sola' },
    potn: ['Iwo Baraniewski', 'Shanelle Dyer'],
  },

  model_notes: 'Accuracy de 84.6% (11/13) em vencedores, o melhor resultado do nosso modelo ate agora. Subiu de 71% (Emmett vs Vallejos) pra 84.6%. Os dois erros (Page/Patterson e Campbell/Silva) revelam padroes importantes: subestimamos a capacidade de Page de defender takedowns e superestimamos o hype de debutantes. A controversia no main event valida nossa previsao mesmo que os scorecards tenham sido questionados. O acerto no azarao Wood vs Keita e um destaque do modelo.',

  quotable_stats: [
    { stat: '84.6%', context: 'Accuracy do modelo nesse card: 11 de 13 vencedores corretos', category: 'model', icon: 'Target', shareable_text: 'Nosso modelo acertou 11 de 13 vencedores no UFC Londres (84.6%). Subimos de 71% pra 84.6% em dois eventos.' },
    { stat: '0:28', context: 'Tempo que Baraniewski precisou pra nocautear Lane e faturar $100K', category: 'finish', icon: 'Zap', fighter: 'Baraniewski', shareable_text: 'Baraniewski nocauteou Lane em 28 SEGUNDOS no UFC Londres. $100K de bonus. 8-0 com 3 nocautes no R1 seguidos.' },
    { stat: '20-0', context: 'Record de Evloev apos a vitoria controversa sobre Murphy', category: 'streak', icon: 'TrendingUp', fighter: 'Evloev', shareable_text: 'Movsar Evloev e agora 20-0 na carreira. 10 vitorias consecutivas no UFC. Proximo passo: titulo peso-pena.' },
    { stat: '4-0', context: 'Sequencia de vitorias de Duncan que o coloca no ranking pela primeira vez', category: 'breakout', icon: 'Sparkles', fighter: 'Duncan', shareable_text: 'Christian Leroy Duncan: 4 vitorias seguidas no UFC. Entra no ranking do peso-medio pela primeira vez. O britanico mais perigoso da divisao.' },
    { stat: '$400K', context: 'Total de bonus distribuidos no card: 2x POTN ($100K cada) + 1x FOTN ($100K cada lutador)', category: 'bonus', icon: 'BarChart3', shareable_text: 'UFC Londres distribuiu $400K em bonus: Baraniewski ($100K), Dyer ($100K), Jones ($100K), Sola ($100K). Card generoso.' },
    { stat: '1a derrota', context: 'Murphy sofre a primeira derrota da carreira apos 17 vitorias e 1 empate', category: 'historical', icon: 'AlertTriangle', fighter: 'Murphy', shareable_text: 'Lerone Murphy sofre a 1a derrota da carreira em decisao controversa. De 17-0-1 pra 17-1-1. O tiroteio nao o parou, mas os juizes sim.' },
  ],

  narrative_threads: [
    {
      headline: 'A Controversia Que Pode Mudar o Peso-Pena',
      slug_tag: 'RIVALRY',
      fighters_involved: ['Evloev', 'Murphy'],
      lede: 'Evloev venceu, mas Murphy pode ter sido roubado. Os scorecards do main event dividiram a comunidade MMA.',
      body: 'Os numeros contam uma historia. Murphy pareceu dominar os rounds 1 e 2 no striking, com contragolpes precisos e chutes variados. No R3, uma aparente lesao no quadril limitou Murphy. No R4, Evloev levou ponto descontado por golpe baixo, mas dois dos tres juizes ainda deram a luta pra ele. Um juiz deu empate (47-47). Aljamain Sterling, ex-campeao peso-galo, questionou publicamente como os juizes chegaram nesses numeros. A pergunta que fica: Murphy merece uma revanche imediata ou Evloev vai direto pro titulo?',
      suggested_angles: ['Analise round-by-round com scorecards', 'Compilacao de reacoes de lutadores e analistas', 'O historico de decisoes controversas no UFC', 'Murphy merece revanche?'],
      content_type_fit: ['article', 'video', 'podcast', 'social'],
    },
    {
      headline: 'A Pantera Rosa Caiu: O Que Deu Errado no Debut de Campbell',
      slug_tag: 'UPSET',
      fighters_involved: ['Campbell', 'Silva'],
      lede: 'O prospect mais hypado do card foi nocauteado no R2 pelo veterano que ninguem esperava.',
      body: 'Kurtis Campbell entrou no O2 Arena como o debut mais esperado da noite. 8-0, 63% de KO rate, contrato do Contender Series, torcida de Liverpool em peso. Tudo alinhado pra uma estreia espetacular. Danny Silva tinha outros planos. O americano de Santa Ana conectou um gancho de direita que derrubou Campbell, e quando a Pantera Rosa tentou se levantar, mais dois diretos selaram o nocaute. O silencio de 20 mil pessoas no O2 Arena disse tudo. Esse e o lembrete mais duro do MMA: hype nao ganha lutas.',
      suggested_angles: ['A psicologia do debut: por que prospects congelam', 'Silva como o spoiler perfeito', 'O que vem a seguir pra Campbell depois da primeira derrota'],
      content_type_fit: ['article', 'video', 'social'],
    },
    {
      headline: 'Baraniewski: O Homem de 28 Segundos e $100K',
      slug_tag: 'BREAKOUT',
      fighters_involved: ['Baraniewski'],
      lede: 'Tres lutas profissionais. Tres nocautes no primeiro round. Um bonus de $100K. O polones e real.',
      body: 'Iwo Baraniewski nao precisa de apresentacao. Precisa de menos de 30 segundos. O judoca polones de 27 anos conectou um combo de dois socos que desligou Austen Lane em 28 segundos, adicionando mais um finish relampago ao curriculo que ja inclui um nocaute de 20 segundos no DWCS. O O2 Arena mal teve tempo de se sentar. O UFC reconheceu com $100K de Performance da Noite. A 8-0 com todos os finishes no R1, Baraniewski e o prospect mais assustador do meio-pesado. A unica pergunta e: quem vai ser o proximo a durar menos de um minuto?',
      suggested_angles: ['Compilacao dos 3 nocautes de Baraniewski com tempos', 'O background de judo e como ele gera poder', 'Quem e o proximo oponente ideal'],
      content_type_fit: ['video', 'social'],
    },
    {
      headline: 'MVP Vence, Dana Sai, Ninguem Ganha',
      slug_tag: 'LEGACY',
      fighters_involved: ['Page', 'Patterson'],
      lede: 'Page defendeu os takedowns, venceu a decisao, e fez Dana White sair da arena. Uma vitoria sem vencedores.',
      body: 'A narrativa era irresistivel: o sparring partner que conhecia todos os segredos contra o showman veterano. A realidade foi uma luta onde nenhum dos dois arriscou o suficiente. Page defendeu os takedowns de Patterson e controlou a distancia com contragolpes esporadicos. Patterson nao conseguiu implementar o grappling e se frustrou. Dana White literalmente saiu da arena durante a luta. A decisao unanime (30-27, 29-28, 29-28) foi justa mas irrelevante: ninguem saiu dessa luta com mais valor do que entrou.',
      suggested_angles: ['Reagir ao Dana White saindo da arena', 'O padrao de Page contra grapplers mudou?', 'Patterson precisa de mais do que familiaridade'],
      content_type_fit: ['video', 'podcast', 'social'],
    },
  ],

  creator_kit: {
    instagram: [
      { slide_number: 1, title: 'UFC LONDRES: RESULTADOS', content: '11 DE 13 PREVISOES CORRETAS\n84.6% DE ACCURACY\n\nEvloev vence por decisao controversa\nBaraniewski nocauteia em 28 SEGUNDOS\nSilva da o upset do card\n\nSwipe pra ver os resultados completos.', color: 'red' },
      { slide_number: 2, title: 'MAIN EVENT: CONTROVERSIA', content: 'EVLOEV venceu MURPHY\nDecisao Majoritaria\n48-46, 48-46, 47-47\n\nPonto descontado no R4\nMurphy lesionou o quadril no R3\nComunidade MMA dividida\n\nEvloev 20-0. Proximo: TITULO.', color: 'red' },
      { slide_number: 3, title: 'O UPSET DA NOITE', content: 'DANNY SILVA nocauteou\nKURTIS CAMPBELL no R2\n\nA Pantera Rosa de Liverpool\nsofreu a 1a derrota da carreira\nno debut do UFC.\n\nGancho de direita. Silencio total.', color: 'blue' },
      { slide_number: 4, title: 'FINISH DA NOITE', content: 'BARANIEWSKI vs LANE\n28 SEGUNDOS. TKO R1.\n\n$100K de bonus.\n8-0 na carreira.\n3 nocautes no R1 seguidos.\n\nO polones e REAL.', color: 'gold' },
      { slide_number: 5, title: 'NOSSO MODELO', content: 'ACCURACY: 84.6%\n11 de 13 corretos\n\nACERTOS DESTAQUE:\nEvloev por decisao\nWood como azarao (+190)\nBaraniewski KO R1\nPericic KO R1\n\nERROS:\nPage/Patterson\nCampbell/Silva', color: 'green' },
    ],
    twitter: [
      { num: '1/8', text: 'UFC Londres resultados: 11 de 13 previsoes corretas (84.6%). A maior accuracy do nosso modelo. Mas o card teve de TUDO. Thread completa:', type: 'thread_opener' },
      { num: '2/8', text: 'MAIN EVENT: Evloev vence Murphy por decisao MAJORITARIA controversa (48-46, 48-46, 47-47). Ponto descontado no R4. Lesao de quadril no R3. Aljamain Sterling questiona os juizes. Evloev 20-0 e quer o titulo.', type: 'result' },
      { num: '3/8', text: 'UPSET: Danny Silva NOCAUTEOU Kurtis Campbell no R2. A Pantera Rosa de Liverpool sofreu a primeira derrota da carreira no debut. Gancho de direita devastador. 20 mil pessoas em silencio.', type: 'result' },
      { num: '4/8', text: 'FINISH DA NOITE: Baraniewski nocauteou Lane em 28 SEGUNDOS. $100K de bonus. 8-0 com 3 KOs no R1 seguidos. O prospect mais assustador do meio-pesado.', type: 'stat' },
      { num: '5/8', text: 'NOSSO MAIOR ERRO: Previmos Patterson sobre Page. MVP defendeu TUDO. Controlou a distancia. Venceu 30-27. Dana White saiu da arena durante a luta. A familiaridade do sparring funcionou pros DOIS lados.', type: 'hot_take' },
      { num: '6/8', text: 'ACERTO DO CARD: Previmos Wood como azarao a +190 sobre Keita. Wood venceu por decisao dividida. Veteranismo > hype de estreante. O call mais valioso da noite.', type: 'stat' },
      { num: '7/8', text: 'Jones vs Sola: GUERRA DO ANO. Fight of the Night. $100K pra cada. Sangue, trocacao, 3 rounds insanos. Exatamente como previmos: Jones por decisao.', type: 'result' },
      { num: '8/8', text: 'De 71% (Emmett vs Vallejos) pra 84.6% (Evloev vs Murphy). O modelo esta melhorando. Mas Page vs Patterson e Campbell vs Silva mostram: nunca subestime o veterano e nunca aposte tudo no debut.', type: 'thread_closer' },
    ],
    video_script: [
      { time: '0-10s', title: 'Hook', text: '11 de 13. Oitenta e quatro porcento. Nosso modelo acertou quase tudo no UFC Londres. Mas os dois erros contam uma historia ainda mais importante.', b_roll_suggestion: 'Montagem rapida: Baraniewski KO, Silva KO em Campbell, Evloev mao levantada' },
      { time: '10-30s', title: 'Main Event', text: 'Evloev venceu Murphy por decisao controversa. Ponto descontado no R4, Murphy com lesao no quadril no R3, e scorecards que dividiram o mundo do MMA. Nos previmos Evloev por decisao. Acertamos. Mas essa luta merece uma revanche.', b_roll_suggestion: 'Highlights Evloev wrestling R5, Murphy striking R2, momento do golpe baixo' },
      { time: '30-50s', title: 'Os Highlights', text: 'Baraniewski em 28 segundos, $100K de bonus. Dyer com head kick no debut, mais $100K. Jones vs Sola, a guerra do ano. E Danny Silva que calou 20 mil pessoas nocauteando Campbell.', b_roll_suggestion: 'Quick cuts de cada highlight, 3 segundos cada' },
      { time: '50-70s', title: 'Nossos Erros', text: 'Erramos Page vs Patterson. MVP defendeu os takedowns e controlou. E erramos Campbell. O debut e imprevisivel e Danny Silva provou isso. Licoes aprendidas: nunca aposte contra a experiencia do veterano.', b_roll_suggestion: 'Page defendendo takedown, Silva celebrando KO' },
      { time: '70-80s', title: 'CTA', text: 'De 71 pra 84 porcento. O modelo esta melhorando. Proximo card ja tem analise pre-fight em andamento. Segue pra nao perder.', b_roll_suggestion: 'Tela com accuracy audit visual' },
    ],
    tiktok: [
      { hook: 'Acertamos 11 de 13 no UFC Londres. Mas os 2 erros sao a parte mais interessante.', body: 'Previmos Patterson sobre Page. MVP defendeu TUDO e Dana White saiu da arena de tedio. Previmos Campbell no debut. Danny Silva nocauteou a Pantera Rosa em 30 segundos do R2. Licao: nunca aposte contra o veterano e nunca aposte tudo no debut. Mas acertamos Evloev, Baraniewski em 28 segundos, Wood como azarao, e mais 8. 84.6% de accuracy.', cta: 'Qual foi o resultado que mais te surpreendeu? Comenta!' },
      { hook: '28 SEGUNDOS e 100 MIL DOLARES.', body: 'Baraniewski. Lane. Combo de dois socos. Chao. Arbitro para. 28 segundos. $100K de bonus. 8-0 na carreira. 3 nocautes no R1 seguidos. O prospect mais assustador do UFC. E nos previmos EXATAMENTE isso.', cta: 'Quem aguenta o Baraniewski? Comenta!' },
      { hook: '20 mil pessoas ficaram em SILENCIO.', body: 'Kurtis Campbell, a Pantera Rosa de Liverpool. 8-0, invicto, debut dos sonhos em casa. Danny Silva conectou um gancho de direita no R2. Campbell caiu. Mais dois socos. TKO. A primeira derrota da carreira. O O2 Arena ficou mudo. O MMA e cruel.', cta: 'Voce acreditava no hype? Comenta!' },
    ],
    podcast_talking_points: [
      { segment: 'Abertura', duration_suggestion: '3 min', talking_points: ['84.6% de accuracy: 11 de 13 vencedores corretos', 'Subimos de 71% (Emmett/Vallejos) pra 84.6%', 'Card teve controversia, upset, nocaute relampago e guerra'], hot_take: 'Se Murphy tivesse vencido, ninguem reclamaria. Mas os juizes viram algo que nos nao vimos.' },
      { segment: 'Main Event Controverso', duration_suggestion: '8 min', talking_points: ['Scorecards 48-46, 48-46, 47-47: o que os juizes viram', 'Murphy dominou R1-R2 no striking mas a lesao do quadril no R3 mudou tudo', 'Ponto descontado de Evloev no R4 por golpe baixo', 'Evloev 20-0 e quer o titulo. Murphy merece revanche?'], hot_take: 'A revanche tem que acontecer. Essa luta foi boa demais e controversa demais pra nao ter continuacao.' },
      { segment: 'Upsets e Surpresas', duration_suggestion: '5 min', talking_points: ['Silva nocauteando Campbell: por que debuts sao imprevisiveis', 'Page defendendo takedowns de Patterson: o sparring partner nao foi suficiente', 'Dana White saindo da arena: o que isso diz sobre Page'], hot_take: 'Campbell vai voltar melhor. A primeira derrota faz mais pelo crescimento do que 8 vitorias.' },
      { segment: 'Destaques e Bonus', duration_suggestion: '5 min', talking_points: ['Baraniewski: 28 segundos, $100K, o prospect mais explosivo', 'Jones vs Sola: Fight of the Night, guerra sangrenta', 'Dyer: head kick no debut, $100K, a proxima estrela do strawweight', 'Duncan: 4 vitorias seguidas, entra no ranking do MW'] },
      { segment: 'Model Autopsy', duration_suggestion: '4 min', talking_points: ['Os 2 erros: Page/Patterson e Campbell/Silva', 'Licao 1: Page provou que conhecer o adversario funciona pros dois lados', 'Licao 2: Nunca apostar pesado em debutantes, mesmo invictos', 'Acerto destaque: Wood como azarao a +190 sobre Keita'] },
    ],
  },

  model_autopsy: {
    overall_grade: 'A-',
    grade_context: '84.6% de accuracy em vencedores (11/13) e o melhor resultado do modelo. Subimos de 71% no card anterior. Os erros foram informativos e revelam padroes claros pra melhorar.',
    correct_calls: [
      { fight: 'Evloev vs Murphy', predicted: 'Evloev por Decisao', actual: 'Evloev por Decisao Majoritaria', confidence_label: 'MEDIA', analysis: 'Acerto preciso. A tese do wrestling controlando os rounds finais se confirmou, especialmente no R5 com o takedown importante. A controversia dos scorecards nao invalida a previsao.' },
      { fight: 'Baraniewski vs Lane', predicted: 'Baraniewski KO R1', actual: 'Baraniewski TKO R1 (0:28)', confidence_label: 'MEDIA-ALTA', analysis: 'Acerto perfeito em vencedor, metodo e round. A convergencia de finalizacoes rapidas de ambos se materializou exatamente como previsto.' },
      { fight: 'Wood vs Keita', predicted: 'Wood por Decisao (azarao +190)', actual: 'Wood por Decisao Dividida', confidence_label: 'MEDIA', analysis: 'O melhor call do card. Fomos contra o mercado baseados no veteranismo de Wood e nos problemas de peso de Keita. Se confirmou.' },
    ],
    wrong_calls: [
      { fight: 'Page vs Patterson', predicted: 'Patterson por Decisao', actual: 'Page por Decisao Unanime', confidence_label: 'MEDIA', analysis: 'Subestimamos a capacidade de Page de defender takedowns contra Patterson especificamente. O padrao Garry/Storley nao se repetiu porque Page TAMBEM conhecia o jogo de Patterson dos treinos. A familiaridade do sparring funcionou pros dois lados, nao so pro Patterson.', error_type: 'stylistic_misread' },
      { fight: 'Campbell vs Silva', predicted: 'Campbell KO R1-R2', actual: 'Silva TKO R2', confidence_label: 'MEDIA', analysis: 'Superestimamos o hype do debutante e subestimamos Silva. Ironicamente, previmos KO R1-R2 e o KO aconteceu no R2, mas pro lado errado. Debut no UFC com torcida em casa pode pesar mais do que ajudar.', error_type: 'momentum_miss' },
    ],
    patterns_learned: [
      { pattern: 'Familiaridade de treino e faca de dois gumes', evidence: 'Page defendeu Patterson porque tambem conhecia o jogo do adversario. O argumento de "sparring partner advantage" se provou neutro.', adjustment: 'Em lutas futuras entre ex-parceiros de treino, tratar a familiaridade como fator neutro, nao como vantagem pra nenhum dos dois.' },
      { pattern: 'Debuts com hype sao mais arriscados do que parecem', evidence: 'Campbell foi nocauteado no debut apesar de ser favorito -220. A pressao do debut em casa pode ter sido negativa.', adjustment: 'Reduzir confianca em previsoes de debutantes favoritos, especialmente em casa. A pressao do debut e um fator subestimado.' },
      { pattern: 'Previsoes de KO vs Decisao: o queixo e imprevisivel', evidence: '5 de 8 previsoes de KO resultaram em decisao. Trocoli, Franco, Aswell, Rock e Duncan mostraram mais resistencia do que esperado.', adjustment: 'Ser mais conservador com previsoes de metodo KO. Queixo e resistencia sao os fatores mais dificeis de prever.' },
    ],
    confidence_calibration: {
      high_confidence_record: '3/3 corretos (Baraniewski, Pericic, Kondratavicius)',
      medium_confidence_record: '8/10 corretos (80%)',
      insight: 'Calibracao forte: previsoes de alta confianca foram 100% corretas. Media confianca teve 2 erros em 10, ambos em lutas com dinamicas imprevisíveis (sparring partner, debut). A calibracao sugere que podemos confiar mais nas picks de alta confianca.',
    },
  },

  division_impacts: [
    {
      division: 'Peso Pena',
      fights_on_card: 5,
      title_picture_impact: 'Evloev (20-0) e agora o desafiante claro ao titulo. Murphy (17-1-1) caiu do top 3 mas permanece relevante. Riley entra no radar como prospect.',
      movers: [
        { fighter: 'Evloev', result: 'W', impact_level: 'high', one_liner: '20-0 e proximo desafiante ao titulo peso-pena' },
        { fighter: 'Murphy', result: 'L', impact_level: 'high', one_liner: 'Primeira derrota controversa, cai do top 3 mas merece revanche' },
        { fighter: 'Riley', result: 'W', impact_level: 'medium', one_liner: '13-0, dominou Aswell, prospect britanico mais promissor' },
        { fighter: 'Silva', result: 'W', impact_level: 'medium', one_liner: 'Upset sobre Campbell, ganha relevancia na divisao' },
      ],
      narrative: 'O peso-pena saiu de Londres com um novo desafiante ao titulo (Evloev) e uma controversia que pode gerar revanche. Riley e o prospect a observar.',
    },
    {
      division: 'Peso Medio',
      fights_on_card: 2,
      title_picture_impact: 'Duncan entra no ranking pela primeira vez com 4 vitorias seguidas sobre um ex-top 10.',
      movers: [
        { fighter: 'Duncan', result: 'W', impact_level: 'high', one_liner: '14-2, 4 vitorias seguidas, entra no top 15 do ranking' },
        { fighter: 'Dolidze', result: 'L', impact_level: 'medium', one_liner: '15-5, segunda derrota em 3 lutas, pode sair do top 15' },
      ],
      narrative: 'Duncan confirma a ascensao e agora precisa de um top 10 pra validar. Dolidze aos 37 anos parece em declinio.',
    },
    {
      division: 'Peso Meio-Pesado',
      fights_on_card: 1,
      title_picture_impact: 'Baraniewski ainda nao e ranqueado mas com 8-0 e 3 KOs no R1, vai entrar no radar rapidamente.',
      movers: [
        { fighter: 'Baraniewski', result: 'W', impact_level: 'medium', one_liner: '8-0, 3 KOs no R1 seguidos, prospect mais explosivo da divisao' },
      ],
      narrative: 'Baraniewski precisa de um oponente ranqueado pra confirmar. O meio-pesado tem um novo nome assustador.',
    },
  ],

  replay_guide: [
    { slug: 'jones-vs-sola', fighter1: 'Jones', fighter2: 'Sola', rewatch_rating: 5, rewatch_label: 'Must Watch', category: 'war', why_watch: 'Fight of the Night por uma razao. Tres rounds de guerra sangrenta com trocacao pesada. Jones e Sola deram tudo.', key_moments: [{ timestamp: 'R1 2:30', description: 'Sola conecta combo pesado', moment_type: 'exchange' }, { timestamp: 'R2 4:00', description: 'Jones responde com cotovelos', moment_type: 'exchange' }] },
    { slug: 'evloev-vs-murphy', fighter1: 'Evloev', fighter2: 'Murphy', rewatch_rating: 4, rewatch_label: 'Worth It', category: 'technical', why_watch: 'Main event controverso com 5 rounds competitivos. Murphy dominando no striking, Evloev controlando no wrestling. Ponto descontado no R4 muda tudo.', key_moments: [{ timestamp: 'R3 3:00', description: 'Murphy lesiona o quadril', moment_type: 'exchange' }, { timestamp: 'R4 0:30', description: 'Golpe baixo de Evloev, ponto descontado', moment_type: 'exchange' }, { timestamp: 'R5 2:00', description: 'Takedown importante de Evloev', moment_type: 'takedown' }] },
    { slug: 'baraniewski-vs-lane', fighter1: 'Baraniewski', fighter2: 'Lane', rewatch_rating: 4, rewatch_label: 'Worth It', category: 'finish', why_watch: '28 segundos. Performance da Noite. Assista so pra ver a velocidade do combo que desligou Lane.', key_moments: [{ timestamp: 'R1 0:25', description: 'Combo de dois socos derruba Lane', moment_type: 'knockdown' }, { timestamp: 'R1 0:28', description: 'Ground and pound, TKO', moment_type: 'finish' }] },
    { slug: 'campbell-vs-silva', fighter1: 'Campbell', fighter2: 'Silva', rewatch_rating: 4, rewatch_label: 'Worth It', category: 'upset', why_watch: 'O upset do card. A Pantera Rosa sofre a primeira derrota em um debut brutal. O gancho de direita de Silva e assustador.', key_moments: [{ timestamp: 'R2 0:20', description: 'Gancho de direita de Silva derruba Campbell', moment_type: 'knockdown' }, { timestamp: 'R2 0:31', description: 'TKO com socos adicionais', moment_type: 'finish' }] },
    { slug: 'dyer-vs-oliveira', fighter1: 'Dyer', fighter2: 'Oliveira', rewatch_rating: 3, rewatch_label: 'Good', category: 'finish', why_watch: 'Head kick espetacular de Dyer no debut. Performance da Noite e $100K. Um highlight real.', key_moments: [{ timestamp: 'R2 1:10', description: 'Head kick conecta limpo', moment_type: 'knockdown' }, { timestamp: 'R2 1:17', description: 'Socos adicionais, TKO', moment_type: 'finish' }] },
    { slug: 'page-vs-patterson', fighter1: 'Page', fighter2: 'Patterson', rewatch_rating: 1, rewatch_label: 'Skip', category: 'boring', why_watch: 'So assista se voce quer entender por que Dana White saiu da arena. Pouca acao, Page controlou a distancia e Patterson nao conseguiu o takedown.', key_moments: [] },
  ],

  event_creator_kit: {
    instagram: {
      meta: {
        algorithm_tip: 'Posts de resultados performam melhor nas primeiras 2 horas pos-evento. Carroseis com reacoes e controversias geram 3x mais saves. O algoritmo prioriza conteudo de trending topics.',
        target_metric: '4%+ taxa de save (resultados sao altamente salvaveis)',
        content_type: 'Carrossel pos-evento de 10 slides (resultados + narrativas + accuracy)',
      },
      carousel: [
        { slide_number: 1, slide_type: 'hook', title: 'UFC LONDRES: RESULTADOS', content: 'CONTROVERSIA NO MAIN EVENT\nUPSET DA NOITE\nNOCAUTE EM 28 SEGUNDOS\nDANA WHITE SAIU DA ARENA\n\n13 lutas, 13 historias.\nSwipe pra ver tudo.', visual_note: 'Montagem dos 4 momentos mais impactantes: Evloev mao levantada com Murphy incredulo, Silva KO em Campbell, Baraniewski celebrando, cadeira vazia de Dana.', color: 'red' },
        { slide_number: 2, slide_type: 'content', title: 'A CONTROVERSIA', content: 'EVLOEV venceu MURPHY\nDecisao Majoritaria\n48-46, 48-46, 47-47\n\nMurphy dominou nos primeiros rounds.\nLesionou o quadril no R3.\nEvloev levou ponto descontado no R4.\nMesmo assim, os juizes deram pro russo.\n\nAljamain Sterling: "Como?"', visual_note: 'Split screen: Murphy com expressao de incredulidade vs Evloev com mao levantada. Scorecards sobrepostos.', color: 'red' },
        { slide_number: 3, slide_type: 'content', title: 'O SILENCIO DO O2 ARENA', content: 'DANNY SILVA nocauteou\nKURTIS CAMPBELL\nTKO R2 (0:31)\n\nA Pantera Rosa de Liverpool.\n8-0, invicta, debut dos sonhos.\nGancho de direita. Chao.\nPrimeira derrota da carreira.\n\n20 mil pessoas em silencio.', visual_note: 'Silva celebrando enquanto Campbell esta no chao. Contraste entre o silencio da torcida e a celebracao.', color: 'blue' },
        { slide_number: 4, slide_type: 'stat', title: '28 SEGUNDOS', content: 'BARANIEWSKI TKO Lane\nR1, 0:28\n\nCombo de 2 socos.\nChao. Ground and pound. Acabou.\n$100K de bonus.\n\n8-0 na carreira.\n3 nocautes no R1 seguidos.\nO prospect mais assustador do UFC.', visual_note: 'Sequencia frame-by-frame do combo. Timer mostrando 0:28.', color: 'gold' },
        { slide_number: 5, slide_type: 'content', title: 'DANA SAIU DA ARENA', content: 'PAGE vs PATTERSON\nDecisao Unanime (30-27, 29-28, 29-28)\n\nPage defendeu os takedowns.\nPatterson nao conseguiu o grappling.\nPouca acao. Pouca emocao.\n\nDana White SAIU DA ARENA\ndurante a luta.\n\nIsso diz tudo.', visual_note: 'MVP com postura de karate vs Patterson frustrado. Texto de "Dana White left the arena" como manchete.', color: 'blue' },
        { slide_number: 6, slide_type: 'content', title: 'HEAD KICK NO DEBUT', content: 'SHANELLE DYER\nTKO R2 (1:17)\nHead kick + socos\n\n$100K Performance da Noite\nDebut no UFC em casa\nA britanica chegou com TUDO.\n\nDe perder no DWCS a bonus\nno debut. Que historia.', visual_note: 'Dyer celebrando com a torcida. Replay do head kick.', color: 'gold' },
        { slide_number: 7, slide_type: 'content', title: 'GUERRA DO ANO', content: 'JONES vs SOLA\nFight of the Night\n$100K pra CADA\n\n3 rounds de trocacao insana.\nSangue, suor, e corage.\nJones por Decisao Unanime.\n\nSe voce nao assistiu,\nassista agora.', visual_note: 'Jones e Sola trocando no R3, ambos sangrando. Badge FOTN.', color: 'red' },
        { slide_number: 8, slide_type: 'stat', title: 'NOSSO MODELO', content: '84.6% DE ACCURACY\n11 de 13 vencedores corretos\n\nSUBIMOS de 71% (card anterior)\npra 84.6% nesse card.\n\nMELHOR CALL:\nWood azarao a +190\nacertamos.\n\nERROS:\nPage/Patterson\nCampbell/Silva', visual_note: 'Graficos de accuracy com barra verde grande (84.6%) e comparacao com 71% anterior.', color: 'green' },
        { slide_number: 9, slide_type: 'prediction', title: 'O QUE VEM A SEGUIR', content: 'EVLOEV: vai lutar pelo TITULO\nMURPHY: merece revanche?\nDUNCAN: entra no ranking MW\nRILEY: 13-0, proximo prospect\nCAMPBELL: volta de derrota\nBARANIEWSKI: quem segura?', visual_note: 'Grid com fotos dos lutadores e setas indicando direcao (up/down/title).', color: 'red' },
        { slide_number: 10, slide_type: 'cta', title: 'RECAP COMPLETO', content: 'Recap completo com:\n\nResultados de todas as 13 lutas\nAccuracy audit do modelo\nNarrativas pos-evento\nReplay guide (o que reassistir)\nModel autopsy (nossos erros)\nCreator kit pos-evento\n\nLink na bio.', visual_note: 'Screenshot do site com o recap. CTA bold.', color: 'gold' },
      ],
      caption: 'UFC Londres terminou e o card entregou TUDO: controversia no main event, upset que silenciou 20 mil pessoas, nocaute em 28 segundos, Dana White saindo da arena, e uma guerra que rendeu Fight of the Night.\n\nNosso modelo acertou 11 de 13 (84.6%). Os 2 erros nos ensinaram licoes importantes.\n\nSwipe pra ver os resultados, highlights, e o que vem a seguir pra cada lutador.\n\nSalva pra referencia.',
      hashtags: ['UFC', 'UFCLondon', 'UFCResults', 'MMA', 'EvloevMurphy', 'UFCLondres', 'MMABrasil', 'FightNight', 'UFCHighlights'],
      best_posting_time: 'Imediatamente pos-evento (janela de 2h) ou domingo de manha (recap)',
    },
    tiktok: {
      meta: {
        algorithm_tip: 'Conteudo de resultados esportivos tem janela viral de 6-12 horas. Hooks com controversia ou upset performam 4x mais. Rewatches aumentam quando voce mostra algo que o viewer quer ver de novo.',
        target_metric: '80%+ retencao (conteudo pos-evento e altamente engajante)',
        content_type: '4 scripts com angulos diferentes (controversia, upset, highlight, accuracy)',
      },
      scripts: [
        {
          script_number: 1,
          angle: 'A Controversia do Main Event',
          hook_3s: 'Os juizes ROUBARAM o Murphy? Ou Evloev mereceu?',
          body: 'Evloev vs Murphy. 5 rounds. Murphy pareceu dominar o striking nos 2 primeiros. No R3, lesionou o quadril. No R4, Evloev levou ponto descontado por golpe baixo. Mesmo assim, 2 de 3 juizes deram pro Evloev. 48-46, 48-46, 47-47. Aljamain Sterling, ex-campeao, disse: "como?" A primeira derrota da carreira de Murphy veio de forma CONTROVERSA. E agora Evloev e 20-0 e quer o titulo.',
          twist_or_loop: 'Terminar com os scorecards na tela e a pergunta "voce concorda?" pra gerar rewatches e comentarios.',
          cta: 'Roubo ou decisao justa? Comenta!',
          estimated_duration: '50-65s',
        },
        {
          script_number: 2,
          angle: 'O Silencio de 20 Mil Pessoas',
          hook_3s: '20 mil pessoas ficaram em SILENCIO no O2 Arena.',
          body: 'Kurtis Campbell. A Pantera Rosa de Liverpool. 8-0. Invicto. Debut dos sonhos em casa. A torcida de Liverpool em peso. Tudo alinhado pra uma estreia espetacular. Danny Silva conectou um gancho de direita no R2. Campbell caiu. Mais dois diretos. TKO. A primeira derrota da carreira. O O2 Arena ficou MUDO. 20 mil pessoas em silencio absoluto. O MMA e o esporte mais cruel do mundo.',
          twist_or_loop: 'Mostrar o barulho da torcida ANTES do KO e o silencio DEPOIS. Contraste sonoro brutal.',
          cta: 'Voce acreditava no hype? Comenta!',
          estimated_duration: '45-55s',
        },
        {
          script_number: 3,
          angle: '28 Segundos e $100K',
          hook_3s: 'Esse cara ganhou $100 MIL DOLARES em 28 segundos de trabalho.',
          body: 'Iwo Baraniewski. Combo de dois socos. Austen Lane no chao. Ground and pound. Arbitro para. 28 segundos. Nocaute. $100K de bonus. Faz as contas: isso da $214 mil dolares por MINUTO. 8-0 na carreira. 3 nocautes no R1 seguidos. 20 segundos no DWCS, 89 segundos no debut, 28 segundos ontem. O polones nao sabe o que e segundo round.',
          twist_or_loop: 'No final, mostrar um timer contando 28 segundos em tempo real pra audiencia sentir quao rapido foi.',
          cta: 'Quem aguenta esse cara? Comenta!',
          estimated_duration: '40-50s',
        },
        {
          script_number: 4,
          angle: 'Nosso Modelo Acertou 84%',
          hook_3s: 'Acertamos 11 de 13 no UFC Londres. Os 2 erros sao a parte mais interessante.',
          body: 'Previmos Page sobre Patterson. MVP defendeu TUDO. Dana saiu da arena de tedio. Previmos Campbell no debut. Silva nocauteou em 30 segundos. Mas acertamos Evloev, Baraniewski em 28 segundos, Wood como azarao a +190, e mais 8. Licao: nunca aposte contra o veterano e nunca aposte tudo no debut. De 71% no card anterior pra 84.6% nesse. O modelo esta aprendendo.',
          cta: 'Qual resultado te surpreendeu mais? Comenta!',
          estimated_duration: '45-55s',
        },
      ],
    },
    youtube: {
      meta: {
        algorithm_tip: 'Videos de recap pos-evento tem CTR alto nas primeiras 24h. Thumbnails com expressoes de choque ou controversia performam melhor. Titulos com "controversy", "upset" ou "robbery" geram cliques.',
        target_metric: '12%+ CTR (trending topic boost), 50%+ retencao',
        content_type: 'Video de 12-15 minutos com resultados, analise, e accuracy audit',
      },
      title_options: [
        'UFC Londres: CONTROVERSIA no Main Event e o Upset que Silenciou 20 Mil Pessoas',
        'Acertamos 84% do UFC Londres, Mas os 2 Erros Ensinaram TUDO',
        'UFC Londres Recap: Roubo? Upset? 28 Segundos? Tudo Que Aconteceu',
      ],
      thumbnail: {
        headline: 'ROUBO?',
        subtext: 'UFC Londres',
        visual_concept: 'Murphy com expressao de incredulidade/raiva, scorecards sobrepostos com numeros em vermelho, "ROUBO?" em amarelo grande. Evloev celebrando menor ao fundo.',
      },
      description: 'Recap completo do UFC Londres: a decisao controversa de Evloev vs Murphy, o upset de Danny Silva sobre Campbell, Baraniewski em 28 segundos, Dana White saindo da arena, e nosso accuracy audit (84.6%). Resultados de todas as 13 lutas.\n\nTimestamps abaixo.',
      script_sections: [
        { timestamp: '0:00', title: 'Hook', text: 'Murphy dominou os primeiros rounds. Lesionou o quadril. Evloev levou ponto descontado. E mesmo assim os juizes deram pro Evloev. A primeira derrota de Murphy e CONTROVERSA. E esse nem foi o momento mais chocante da noite.', retention_note: 'Open loop: promete algo mais chocante que o main event.', b_roll: 'Murphy mao na cabeca, Evloev celebrando, scorecards na tela.' },
        { timestamp: '0:30', title: 'Main Event: A Controversia', text: 'Round por round. Murphy dominou o striking nos R1 e R2. No R3, o quadril de Murphy estourou. No R4, golpe baixo de Evloev, ponto descontado. No R5, Evloev completou takedown importante. Os juizes: 48-46, 48-46, 47-47. A comunidade MMA explodiu. Aljamain Sterling questionou publicamente. Murphy merece revanche? Evloev vai direto pro titulo?', retention_note: 'Mostrar scorecards com graficos visuais por round.', b_roll: 'Highlights de cada round, momento do golpe baixo, reacao de Murphy ao resultado.' },
        { timestamp: '3:00', title: 'O Silencio: Silva KO Campbell', text: 'O upset da noite. Campbell entrou como o debut mais hypado. 8-0, 63% KO, Liverpool em peso. Danny Silva conectou um gancho de direita no R2 e o O2 Arena ficou mudo. 20 mil pessoas em silencio. A primeira derrota da Pantera Rosa. Nos erramos essa previsao. Licao: o debut e IMPREVISIVEL.', b_roll: 'O barulho pre-luta, o KO, o silencio da arena. Contraste sonoro.' },
        { timestamp: '5:00', title: 'Baraniewski: 28 Segundos e $100K', text: 'O homem de 28 segundos. Combo de dois socos, Lane no chao, ground and pound, acabou. $100K de bonus. 8-0, 3 KOs no R1 seguidos. 20s no DWCS, 89s no debut, 28s ontem. O polones e o prospect mais assustador do meio-pesado. Nos previmos EXATAMENTE isso.', b_roll: 'Replay do combo, timer de 28 segundos, comparacao dos 3 tempos de KO.' },
        { timestamp: '6:30', title: 'Dana White Saiu da Arena', text: 'Page vs Patterson. A luta que ninguem queria. Page defendeu takedowns, controlou distancia, nao arriscou. Patterson nao conseguiu implementar o grappling. Dana White literalmente se levantou e saiu. Nos previmos Patterson. Erramos. Page provou que conhecer o adversario funciona pros dois lados.', b_roll: 'Page com postura defensiva, Patterson frustrado, manchete sobre Dana saindo.' },
        { timestamp: '8:00', title: 'Destaques do Card', text: 'Dyer com head kick no debut e $100K de bonus. Jones vs Sola, Fight of the Night, guerra sangrenta de 3 rounds. Duncan vence Dolidze por decisao e entra no ranking. Riley domina Aswell em 13-0. Wood vence como azarao. Pericic nocauteia no R1.', b_roll: 'Quick cuts de cada highlight, 3-4 segundos cada.' },
        { timestamp: '10:00', title: 'Accuracy Audit: 84.6%', text: 'Nosso modelo: 11 de 13 corretos. 84.6%. Subimos de 71% no card anterior. Os acertos: Evloev por decisao, Baraniewski KO R1, Wood azarao +190, Jones por decisao, Pericic KO R1. Os erros: Page/Patterson (subestimamos o TDD de Page) e Campbell/Silva (superestimamos o debut). Licoes claras pra melhorar.', retention_note: 'Graficos visuais de accuracy com barras verde/vermelho.', b_roll: 'Tela de scorecard com checks e X, graficos de accuracy.' },
        { timestamp: '12:00', title: 'O Que Vem a Seguir + CTA', text: 'Evloev 20-0 quer o titulo. Murphy merece revanche? Duncan entra no ranking. Baraniewski precisa de um oponente ranqueado. Campbell volta de derrota. O proximo card ja tem analise em andamento. Segue, inscreve, e comenta: o Murphy foi roubado ou nao?', b_roll: 'Graficos de "what\'s next" com setas, poster do proximo evento.' },
      ],
      tags: ['UFC', 'UFC London', 'UFC Results', 'Evloev Murphy', 'UFC Recap', 'MMA', 'UFC Controversy', 'Baraniewski KO', 'Campbell upset', 'UFC Highlights', 'Fight Night'],
    },
    twitter: {
      meta: {
        algorithm_tip: 'Threads de resultados nos primeiros 60 minutos pos-evento tem alcance massivo. Hot takes sobre controversias geram replies (150x mais valioso que likes). Sem links externos.',
        target_metric: '10%+ taxa de reply (controversia natural do card)',
        content_type: 'Thread de 10 tweets + 4 tweets avulsos virais + enquete',
      },
      thread: [
        { num: '1/10', text: 'UFC Londres terminou e esse card entregou TUDO: controversia, upset, nocaute em 28 segundos, Dana saindo da arena, e uma guerra. Nosso modelo acertou 11 de 13 (84.6%). Recap completo:', tweet_type: 'hook', engagement_note: 'Resultados frescos = alcance alto. Poste nos primeiros 60 min.' },
        { num: '2/10', text: 'MAIN EVENT: Evloev vence Murphy por decisao MAJORITARIA (48-46, 48-46, 47-47). Murphy dominou o striking nos R1-R2. Lesionou o quadril no R3. Evloev levou ponto descontado por golpe baixo no R4. Os juizes deram pro Evloev. CONTROVERSIA.', tweet_type: 'content' },
        { num: '3/10', text: 'Aljamain Sterling: "Como os juizes chegaram nesses scorecards?" A comunidade MMA ta dividida. Murphy teve a primeira derrota da carreira de forma controversa. Revanche TEM que acontecer. Evloev 20-0 e quer o titulo.', tweet_type: 'hot_take', engagement_note: 'Hot take gera replies. A controversia e real.' },
        { num: '4/10', text: 'UPSET: Danny Silva nocauteou Campbell no R2 com gancho de direita. A Pantera Rosa, 8-0 invicta, sofreu a primeira derrota da carreira NO DEBUT. 20 mil pessoas em silencio absoluto. O MMA e cruel.', tweet_type: 'content' },
        { num: '5/10', text: 'FINISH: Baraniewski TKO Lane em 28 SEGUNDOS. $100K de bonus. 8-0 com 3 KOs no R1 seguidos. 20s no DWCS, 89s no debut, 28s ontem. O polones nao sabe o que e segundo round.', tweet_type: 'content' },
        { num: '6/10', text: 'Page defendeu os takedowns de Patterson, venceu por decisao (30-27, 29-28, 29-28), e Dana White SAIU DA ARENA durante a luta. Nos previmos Patterson. Erramos. A familiaridade do sparring funcionou pros dois lados.', tweet_type: 'content' },
        { num: '7/10', text: 'FOTN: Jones vs Sola. GUERRA. 3 rounds de trocacao insana. Sangue e corage. $100K pra cada. Se voce nao assistiu, assista AGORA. A melhor luta do ano ate agora.', tweet_type: 'content' },
        { num: '8/10', text: 'Mais destaques: Dyer nocauteia com HEAD KICK no debut ($100K bonus). Duncan vence Dolidze e entra no ranking. Riley 13-0 domina Aswell. Wood vence como AZARAO (+190, nos previmos).', tweet_type: 'content' },
        { num: '9/10', text: 'ACCURACY: 84.6% (11/13). Subimos de 71% pro card anterior. Melhor call: Wood azarao a +190. Piores: Page/Patterson e Campbell/Silva. Licao: nunca aposte contra o veterano e nunca aposte tudo no debut.', tweet_type: 'content' },
        { num: '10/10', text: 'A pergunta que fica: Murphy foi ROUBADO? Responde com SIM ou NAO. Vamos ver o que voces acham.', tweet_type: 'cta', engagement_note: 'Pergunta binaria simples gera MUITOS replies.' },
      ],
      standalone_tweets: [
        'Murphy dominou os primeiros rounds, lesionou o quadril, e Evloev levou ponto descontado. Mesmo assim os juizes deram pro Evloev. A primeira derrota de Murphy e CONTROVERSA. Ele merece revanche.',
        'Baraniewski ganhou $100 MIL DOLARES em 28 segundos de trabalho. Isso da $214K por minuto. 8-0, 3 KOs no R1 seguidos. O cara mais eficiente do UFC.',
        'Danny Silva silenciou 20 MIL PESSOAS nocauteando o invicto Campbell no debut. Gancho de direita. Chao. TKO. A Pantera Rosa caiu. O MMA nao tem script.',
        'Dana White SAIU DA ARENA durante Page vs Patterson. Quando o presidente do UFC sai durante uma luta do seu card, a mensagem e clara.',
      ],
      poll_suggestion: {
        question: 'Murphy foi roubado no UFC Londres?',
        options: ['Sim, Murphy venceu', 'Nao, Evloev mereceu', 'Precisa de revanche', 'Empate justo'],
      },
    },
    podcast: {
      meta: {
        algorithm_tip: 'Episodios de recap pos-evento sao os mais ouvidos no nicho de MMA. Publicar nas primeiras 12 horas maximiza discovery. Momentos clipaveis com hot takes geram shorts/reels.',
        target_metric: '80%+ retencao (audiencia altamente engajada pos-evento)',
        content_type: 'Episodio de 40-50 minutos com 6 segmentos narrativos',
      },
      episode_title: 'UFC Londres Recap: A Controversia, o Silencio, e 28 Segundos',
      episode_description: 'Recap completo do UFC Londres. Evloev vence Murphy em decisao controversa. Silva silencia 20 mil pessoas. Baraniewski em 28 segundos. Dana sai da arena. Jones vs Sola e a guerra do ano. Nosso modelo acertou 84.6%. Os 2 erros nos ensinaram mais do que os 11 acertos.',
      cold_open: 'Vinte mil pessoas gritando o nome de Lerone Murphy. Cinco rounds. Uma lesao no quadril. Um golpe baixo. Um ponto descontado. E no final, os juizes deram a vitoria pro cara que perdeu o ponto. A primeira derrota de Murphy. E a comunidade MMA ainda nao parou de gritar.',
      segments: [
        {
          timestamp: '0:00-5:00',
          title: 'A Controversia: Evloev vs Murphy',
          talking_points: [
            'Round por round: Murphy dominou R1 e R2 no striking com contragolpes e chutes. No R3, o quadril estourou. No R4, golpe baixo de Evloev, ponto descontado. No R5, takedown importante de Evloev.',
            'Os scorecards: 48-46, 48-46, 47-47. Dois juizes deram 3 rounds pro Evloev MESMO com o ponto descontado. Um juiz deu empate.',
            'Sterling, Bisping e a comunidade inteira questionando. Mas por outro lado: Evloev controlou os championship rounds e o takedown do R5 pode ter sido decisivo.',
            'A pergunta: revanche imediata ou Evloev vai direto pro titulo contra Volkanovski/Topuria?',
          ],
          quotable_moment: 'Murphy levou um tiro no rosto em 2013 e sobreviveu. Mas os juizes do UFC em 2026 foram mais dificeis de vencer do que uma bala.',
          hot_take: 'Murphy nao foi roubado. Foi uma luta apertada e os championship rounds importam mais. Evloev controlou o R5 e isso selou. Controverso? Sim. Roubo? Nao.',
          discussion_questions: [
            'Se os juizes tivessem dado pro Murphy, voces teriam reclamado?',
            'Evloev merece ir direto pro titulo ou Murphy merece revanche primeiro?',
          ],
        },
        {
          timestamp: '5:00-10:00',
          title: 'O Silencio: Campbell Caiu',
          talking_points: [
            'Campbell entrou com TUDO: 8-0, torcida, hype, Contender Series. Silva entrou como o cara que ninguem apostava. Gancho de direita no R2. Silencio.',
            'Nos erramos essa. Previmos Campbell por KO. A licao e clara: debuts sao imprevisiveis e o hype pode pesar mais do que ajudar.',
            'Silva agora esta 3-1 no UFC. Esse pode ser o turning point da carreira dele. De "oponente de debut" pra "o cara que parou a Pantera Rosa".',
            'Campbell vai voltar. A primeira derrota pode ser o melhor coisa que aconteceu pra ele a longo prazo. Mas a dor de perder em casa, no debut, e brutal.',
          ],
          quotable_moment: 'O O2 Arena passou de terremoto pra cemiterio em 0.5 segundo. Um gancho de direita. Silencio. A Pantera Rosa aprendeu que o UFC nao respeita hype.',
          discussion_questions: [
            'Campbell vai voltar mais forte ou a derrota no debut vai marca-lo?',
            'Silva como o "debut spoiler" e um papel que tem valor na divisao?',
          ],
        },
        {
          timestamp: '10:00-15:00',
          title: 'Baraniewski, Dyer, e os Finishes',
          talking_points: [
            'Baraniewski em 28 segundos. Terceiro KO no R1 seguido. O cara e absurdo. A questao agora e: quem e o proximo? Ele precisa de um ranqueado.',
            'Dyer com head kick no debut e $100K. De perder no DWCS e ganhar contrato mesmo assim, pra nocautear na estreia. Uma das melhores historias da noite.',
            'Pericic TKO R1 sobre Sutherland. O pupilo do City Kickboxing (Adesanya, Volkanovski) continua impressionando nos pesados.',
            '$400K em bonus no card. Baraniewski $100K, Dyer $100K, Jones $100K, Sola $100K. London pagou bem.',
          ],
          quotable_moment: 'Baraniewski ganha $100K em 28 segundos. Isso da $214 mil por minuto. Eu escolhi a profissao errada.',
          discussion_questions: [
            'Baraniewski pode chegar ao top 5 do meio-pesado em 2026?',
          ],
        },
        {
          timestamp: '15:00-22:00',
          title: 'Page/Patterson e os Resultados que Ninguem Esperava',
          talking_points: [
            'Page defendeu TUDO. O padrao Garry/Storley nao se repetiu. A narrativa do sparring partner era irresistivel mas a realidade mostrou: conhecer o adversario funciona pros dois lados.',
            'Dana White saiu da arena durante a luta. Quando o presidente do UFC se levanta e sai, a mensagem e devastadora. Page pode ter vencido a luta mas perdeu algo mais importante: o interesse do UFC.',
            'Duncan venceu Dolidze por decisao (29-28 x3) em vez do KO que previmos. CLD esta mais completo do que imaginamos. Entra no ranking do peso-medio.',
            'Riley 13-0 dominou Aswell por decisao unanime (30-27 x3). O nocaute nao veio mas o dominio foi total. O prospect britanico e real.',
          ],
          hot_take: 'Page ganhou a luta mas perdeu o futuro. Dana saindo da arena e pior do que perder por nocaute. Pelo menos nocaute gera views.',
          discussion_questions: [
            'Page tem futuro no UFC depois de Dana sair da arena? Ou vai ser cortado?',
            'Duncan vencendo por decisao em vez de KO e bom ou ruim pra carreira dele?',
          ],
        },
        {
          timestamp: '22:00-30:00',
          title: 'Accuracy Audit e Licoes do Modelo',
          talking_points: [
            'De 71% pra 84.6%. Melhor resultado do modelo. Alta confianca: 3/3 corretos. Media confianca: 8/10.',
            'O melhor call: Wood como azarao a +190 contra Keita. A tese de veteranismo > hype de estreante se confirmou perfeitamente.',
            'Os 2 erros revelam padroes claros: (1) familiaridade de treino e faca de dois gumes, nao vantagem unilateral. (2) Debuts com hype sao mais arriscados do que parecem.',
            'Ajuste pro proximo card: ser mais conservador com previsoes de KO (5 de 8 previsoes de KO resultaram em decisao) e tratar ex-sparring partners como fator neutro.',
          ],
          quotable_moment: 'Os erros sao mais valiosos que os acertos. Page/Patterson nos ensinou que conhecer o adversario funciona pros dois lados. Campbell/Silva nos ensinou que hype nao vence lutas.',
          discussion_questions: [
            '84.6% e um bom numero? Qual e o benchmark que voces consideram "elite"?',
            'Qual dos nossos 2 erros voces acharam mais surpreendente?',
          ],
        },
        {
          timestamp: '30:00-35:00',
          title: 'O Que Vem a Seguir',
          talking_points: [
            'Evloev 20-0 e o desafiante numero 1. Titulo contra Volkanovski ou Topuria. A pergunta e quando, nao se.',
            'Murphy merece revanche? A controversia garante interesse. Mas se Evloev for direto pro titulo, Murphy pode enfrentar Diego Lopes ou Arnold Allen.',
            'Duncan no ranking do peso-medio. Precisa de um top 10 (Whittaker? Costa? Cannonier?) pra validar.',
            'Baraniewski no radar do meio-pesado. O proximo oponente define se ele e prospect ou contender.',
          ],
          discussion_questions: [
            'Revanche Evloev/Murphy ou Evloev direto pro titulo?',
            'Quem deve ser o proximo oponente de Baraniewski?',
          ],
        },
      ],
    },
  } as EventCreatorKitData,
};

export default async function RecapEvloevVsMurphyPage() {
  const enrichedData = await enrichRecapWithPhotos(recapData);
  return <RecapView data={enrichedData} />;
}
